stock/quick_purchase/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('perform_quick_buy/', views.perform_quick_buy),
]

stock/quick_purchase/forms.py
from django import forms

CHOICES = (('1', "btc"), ('2', "eth"))

class QuickBuyForm(forms.Form):
    buy_amount = forms.CharField(max_length=30)
    buy_currency = forms.ChoiceField(choices=CHOICES)
    pay_amount = forms.CharField(max_length=30)
    pay_currency = forms.ChoiceField(choices=CHOICES)

stock/quick_purchase/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from decimal import Decimal
from .forms import QuickBuyForm
from currencies.models import Currency
from portfolio.views import portfolio

def perform_quick_buy(request):
    if request.method == 'POST' and request.user.is_authenticated:
        buy_amount_str = request.POST.get('buy_amount')
        buy_currency_str = request.POST.get('buy_currency')
        pay_currency_str = request.POST.get('pay_currency')
        buy_amount = Decimal(buy_amount_str)
        buy_currency = Currency.objects.get(name=buy_currency_str)
        pay_currency = Currency.objects.get(name=pay_currency_str)
        pay_amount = buy_currency.convert_amount_to(buy_amount, pay_currency)
        print("price:", pay_amount, pay_currency.id)
        if request.user.userwallet.is_solvent(pay_amount, pay_currency):
            print("wyplacalny")
            request.user.userwallet.perform_transaction(pay_amount, pay_currency, buy_amount, buy_currency)
        else:
            print("niewyplacalny")
        # TODO transaction
    return HttpResponse('')

stock/quick_purchase/templates/quick_purchase/quick_purchase_panel.html
{% load static %}
{% load widget_tweaks %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'quick_purchase/quick_purchase_panel.css' %}">
<div class="container-fluid" id="quick-buy-panel">
    <form id="quick-buy-form" method="post" action="/perform_quick_buy/">
        {% csrf_token %}
        <div class="row mb-2 d-flex">
            <div class="col-sm-7" id="quick-buy-text">Quick buy:</div>
            <div class="col-sm-5 text-right">
                <span id="balance-field">
                    <span id="balance-field-placeholder">show balance</span>
                    <span id="balance-field-value">${{ user_balance_context }}</span>
                    <i id="balance-visibility-toggle" class="far fa-eye"></i>
                </span>
            </div>
        </div>
        <div class="row no-gutters d-flex">
            <div class="col-sm-7 form-group">
                <!--<input type="text" name="buy_amount" maxlength="30" placeholder="Buying..." class="form-control" required id="id_buy_amount">!-->
                {{ quick_buy_form.buy_amount|attr:"class:form-control"|attr:"placeholder:Buying..."}}
            </div>
            <div class="col-sm-5 pl-2 form-group">
                <select name="buy_currency" class="form-control" id="id_buy_currency">
                    {% for currency in currencies %}
                    <option value="{{ currency.name }}">{{ currency.symbol|upper }}</option>
                    {% endfor %}
                </select>
                <!--{{ quick_buy_form.buy_currency|attr:"class:form-control" }}!-->
            </div>
        </div>
        <div class="row no-gutters d-flex">
            <div class="form-group col-sm-7">
                <!--{{ quick_buy_form.pay_amount|attr:"class:form-control"|attr:"placeholder:Paying..." }}!-->
                <input type="submit" class="form-control" id="exampleFormControlInput2" value="PAY WITH:">
            </div>
            <div class="form-group col-sm-5 pl-2 d-flex">
                <select name="pay_currency" class="form-control" id="id_pay_currency">
                    {% for available_currency in available_currency_set %}
                    <option value="{{ available_currency.name }}">{{ available_currency.symbol|upper }}</option>
                    {% endfor %}
                </select>
                <!--{{ quick_buy_form.pay_currency|attr:"class:form-control" }}!-->
            </div>
        </div>
    </form>
</div>
<script type="text/javascript" src={% static 'quick_purchase/quick_purchase_panel.js' %}></script>